const db = require('../config/database');
const bcrypt = require('bcrypt');

exports.searchBooks = async (req, res) => {
    try {
        const [books] = await db.execute(
            `SELECT ISBN AS isbn, Title AS title, Selling_Price AS price, Quantity_In_Stock AS stock FROM BOOK`
        );
        res.render('customer/product_list', { books });
    } catch (err) {
        res.status(500).send(err.message);
    }
};

exports.getProfile = async (req, res) => {
    try {
        const [rows] = await db.execute('SELECT * FROM CUSTOMER WHERE Username = ?', [req.session.user.username]);
        res.render('customer/profile', { user: rows[0] });
    } catch (err) {
        res.redirect('/login');
    }
};

exports.updateProfile = async (req, res) => {
    const { username, email, password } = req.body;
    const oldUsername = req.session.user.username;

    try {
        if (password && password.trim() !== '') {
            const hashed = await bcrypt.hash(password, 10);
            await db.execute(
                'UPDATE CUSTOMER SET Username = ?, Email = ?, Password = ? WHERE Username = ?',
                [username, email, hashed, oldUsername]
            );
        } else {
            await db.execute(
                'UPDATE CUSTOMER SET Username = ?, Email = ? WHERE Username = ?',
                [username, email, oldUsername]
            );
        }
        req.session.user.username = username;
        res.redirect('/customer/profile');
    } catch (err) {
        res.status(500).send("Update failed: " + err.message);
    }
};

exports.addToCart = async (req, res) => {
    const { isbn } = req.params;
    const username = req.session.user.username;

    try {
        // 1. Try to find an existing cart
        let [carts] = await db.execute(
            'SELECT Cart_ID FROM SHOPPING_CART WHERE Customer_Username = ?', 
            [username]
        );

        let cartId;

        // 2. If no cart exists, CREATE one first
        if (carts.length === 0) {
            const [result] = await db.execute(
                'INSERT INTO SHOPPING_CART (Customer_Username) VALUES (?)', 
                [username]
            );
            cartId = result.insertId; // Get the new ID generated by MySQL
        } else {
            cartId = carts[0].Cart_ID;
        }

        // 3. Now insert the item into the cart
        await db.execute(
            `INSERT INTO CART_ITEM (Cart_ID, ISBN, Quantity)
             VALUES (?, ?, 1)
             ON DUPLICATE KEY UPDATE Quantity = Quantity + 1`,
            [cartId, isbn]
        );

        res.redirect('/customer/cart');
    } catch (err) {
        console.error(err);
        res.status(500).send("Cart Error: " + err.message);
    }
};

exports.viewCart = async (req, res) => {
    const username = req.session.user.username;
    try {
        const [cart] = await db.execute(
            `SELECT B.ISBN, B.Title, B.Selling_Price AS price, CI.Quantity
             FROM SHOPPING_CART SC
             JOIN CART_ITEM CI ON SC.Cart_ID = CI.Cart_ID
             JOIN BOOK B ON CI.ISBN = B.ISBN
             WHERE SC.Customer_Username = ?`,
            [username]
        );
        res.render('customer/cart', { cart });
    } catch (err) {
        res.status(500).send(err.message);
    }
};

exports.viewOrders = async (req, res) => {
    try {
        const [orders] = await db.execute(
            'SELECT * FROM ORDERS WHERE Customer_Username = ?', 
            [req.session.user.username]
        );
        res.render('customer/order_history', { orders });
    } catch (err) {
        // This will print the error to your console so you can see the column names
        console.error("SQL Error in viewOrders:", err.message);
        res.status(500).send(err.message);
    }
};
exports.logout = (req, res) => {
    req.session.destroy();
    res.redirect('/login');
};

// Add these to the bottom of controllers/customerController.js

// 1. Checkout View
exports.getCheckout = (req, res) => {
    const cart = req.session.cart || [];
    res.render('customer/checkout', { cart, error: null });
};

// 2. Process Checkout (The Database part)
exports.postCheckout = async (req, res) => {
    try {
        // Here you would normally insert into ORDERS and ORDER_ITEM tables
        // For now, let's just clear the cart to stop the crash
        req.session.cart = [];
        res.redirect('/customer/order_history');
    } catch (err) {
        res.status(500).send(err.message);
    }
};

// 3. View Order Details
exports.viewOrderDetails = async (req, res) => {
    const orderId = req.params.id;
    try {
        // This is where you query the specific items in an order
        const [details] = await db.execute(
            'SELECT * FROM ORDER_ITEM WHERE Order_ID = ?', 
            [orderId]
        );
        res.render('customer/orderDetails', { details });
    } catch (err) {
        res.status(500).send(err.message);
    }
};

// 4. Missing removeFromCart (Important!)
exports.removeFromCart = async (req, res) => {
    const { isbn } = req.params;
    try {
        // If you are using the Database Cart logic:
        const [carts] = await db.execute('SELECT Cart_ID FROM SHOPPING_CART WHERE Customer_Username = ?', [req.session.user.username]);
        await db.execute('DELETE FROM CART_ITEM WHERE Cart_ID = ? AND ISBN = ?', [carts[0].Cart_ID, isbn]);
        
        res.redirect('/customer/cart');
    } catch (err) {
        res.status(500).send(err.message);
    }
};
